version: '3.8'

services:
  db:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: example_user_password
    deploy:
    #  placement:
    #    constraints:
    #      - node.labels.region == okeanos
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1G

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: example_user_password
      WORDPRESS_DB_NAME: wordpress
    deploy:
      replicas: 4
    #  placement:
    #    max_replicas_per_node: 1
    #    constraints:
    #      - node.labels.region == okeanos
      resources:
        reservations:
          cpus: '0.5'
          memory: 1G
        limits:
          cpus: '1'
          memory: 2G

  webserver:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - app-network
    deploy:
    #  placement:
    #    constraints:
    #      - node.labels.region == okeanos 
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1G
        
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  wordpress_data: